"""
Schemas package initialization.
Re-exports all schemas for convenient imports.
"""

# Academic schemas
from app.schemas.academic import (  # Level; Chain; Nomenclature; Program; Student Group
    Chain,
    ChainBase,
    ChainCreate,
    ChainUpdate,
    Level,
    LevelBase,
    LevelCreate,
    LevelUpdate,
    Nomenclature,
    NomenclatureBase,
    NomenclatureCreate,
    NomenclatureUpdate,
    Program,
    ProgramBase,
    ProgramCreate,
    ProgramUpdate,
    StudentGroup,
    StudentGroupBase,
    StudentGroupCreate,
    StudentGroupDisable,
    StudentGroupUpdate,
)

# Auth schemas
from app.schemas.auth import (  # Role; User; Authentication
    ChangePasswordRequest,
    LoginRequest,
    Role,
    RoleBase,
    RoleCreate,
    RoleUpdate,
    Token,
    TokenData,
    User,
    UserBase,
    UserCreate,
    UserUpdate,
    UserWithoutPassword,
)

# Common schemas
from app.schemas.common import (
    BaseSchema,
    BulkResponseSchema,
    ErrorDetailSchema,
    IDSchema,
    MessageSchema,
    StatusSchema,
    TimestampSchema,
)

# HR schemas
from app.schemas.hr import (  # Department; Contract; Instructor
    Contract,
    ContractBase,
    ContractCreate,
    ContractUpdate,
    Department,
    DepartmentBase,
    DepartmentCreate,
    DepartmentUpdate,
    Instructor,
    InstructorBase,
    InstructorCreate,
    InstructorUpdate,
    InstructorWorkload,
)

# Infrastructure schemas
from app.schemas.infrastructure import (  # Campus; Classroom; Department-Classroom
    Campus,
    CampusBase,
    CampusCreate,
    CampusUpdate,
    Classroom,
    ClassroomAvailability,
    ClassroomBase,
    ClassroomCreate,
    ClassroomUpdate,
    DepartmentClassroom,
    DepartmentClassroomBase,
    DepartmentClassroomCreate,
    DepartmentClassroomUpdate,
)

# Scheduling schemas
from app.schemas.scheduling import (  # Schedule; Time Block; Day; Day-Time Block; Quarter; Class Schedule
    ClassSchedule,
    ClassScheduleBase,
    ClassScheduleCreate,
    ClassScheduleDetailed,
    ClassScheduleUpdate,
    Day,
    DayBase,
    DayTimeBlock,
    DayTimeBlockBase,
    DayTimeBlockCreate,
    Quarter,
    QuarterBase,
    QuarterCreate,
    QuarterUpdate,
    Schedule,
    ScheduleBase,
    ScheduleConflict,
    ScheduleCreate,
    ScheduleUpdate,
    ScheduleValidation,
    TimeBlock,
    TimeBlockBase,
    TimeBlockCreate,
    TimeBlockUpdate,
)

__all__ = [
    # Common
    "BaseSchema",
    "TimestampSchema",
    "IDSchema",
    "MessageSchema",
    "StatusSchema",
    "ErrorDetailSchema",
    "BulkResponseSchema",
    # Auth
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "Role",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "User",
    "UserWithoutPassword",
    "Token",
    "TokenData",
    "LoginRequest",
    "ChangePasswordRequest",
    # Academic
    "LevelBase",
    "LevelCreate",
    "LevelUpdate",
    "Level",
    "ChainBase",
    "ChainCreate",
    "ChainUpdate",
    "Chain",
    "NomenclatureBase",
    "NomenclatureCreate",
    "NomenclatureUpdate",
    "Nomenclature",
    "ProgramBase",
    "ProgramCreate",
    "ProgramUpdate",
    "Program",
    "StudentGroupBase",
    "StudentGroupCreate",
    "StudentGroupUpdate",
    "StudentGroup",
    "StudentGroupDisable",
    # HR
    "DepartmentBase",
    "DepartmentCreate",
    "DepartmentUpdate",
    "Department",
    "ContractBase",
    "ContractCreate",
    "ContractUpdate",
    "Contract",
    "InstructorBase",
    "InstructorCreate",
    "InstructorUpdate",
    "Instructor",
    "InstructorWorkload",
    # Infrastructure
    "CampusBase",
    "CampusCreate",
    "CampusUpdate",
    "Campus",
    "ClassroomBase",
    "ClassroomCreate",
    "ClassroomUpdate",
    "Classroom",
    "DepartmentClassroomBase",
    "DepartmentClassroomCreate",
    "DepartmentClassroomUpdate",
    "DepartmentClassroom",
    "ClassroomAvailability",
    # Scheduling
    "ScheduleBase",
    "ScheduleCreate",
    "ScheduleUpdate",
    "Schedule",
    "TimeBlockBase",
    "TimeBlockCreate",
    "TimeBlockUpdate",
    "TimeBlock",
    "DayBase",
    "Day",
    "DayTimeBlockBase",
    "DayTimeBlockCreate",
    "DayTimeBlock",
    "QuarterBase",
    "QuarterCreate",
    "QuarterUpdate",
    "Quarter",
    "ClassScheduleBase",
    "ClassScheduleCreate",
    "ClassScheduleUpdate",
    "ClassSchedule",
    "ClassScheduleDetailed",
    "ScheduleConflict",
    "ScheduleValidation",
]
